### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by babafeng** [slowmist/blockchain-threat-intelligence#1]
```bash
> docker run -p 8545:8545 --name="btisp-agent-instance" btisp-agent --bounty 0x1c48d477e400f9a5c90d558ba8728f9c2700d806
btisp-agent version 0.1.1
Listening on: http://0.0.0.0:8545
2019/03/12 05:43:33 {"version":"0.1.1","bounty":"0x1c48d477e400f9a5c90d558ba8728f9c2700d806","time":1552369413}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb8 pc=0x73bd83]

goroutine 15 [running]:
main.(*SLOWMIST).handleConnection(0xc000114300, 0x881880, 0xc00045a008)
        /go/src/github.com/slowmist/blockchain-threat-intelligence/src/main.go:113 +0x143
created by main.main.func1
        /go/src/github.com/slowmist/blockchain-threat-intelligence/src/main.go:208 +0x43d
```

**Comment by Drake4Au** [comment]
https://github.com/slowmist/blockchain-threat-intelligence/issues/1#issue-419812071

**Comment by Drake4Au** [comment]
https://github.com/slowmist/blockchain-threat-intelligence/issues/1#issue-419812071
